// <auto-generated />
using System;
using MagicVillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913110039_SeedTheDataInVillaTable1")]
    partial class SeedTheDataInVillaTable1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaAPI.Model.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Wi-Fi, Air Conditioning",
                            CreatedDate = new DateTime(2025, 9, 13, 16, 30, 38, 584, DateTimeKind.Local).AddTicks(6059),
                            Details = "A luxurious villa with stunning ocean views, private pool, and modern amenities.",
                            ImageUrl = "https://unsplash.com/photos/white-and-grey-concrete-building-near-swimming-pool-under-clear-sky-during-daytime-2d4lAQAlbDA",
                            Name = "Azure Haven Villa",
                            Occupancy = 8,
                            Rate = 5000.0,
                            Sqft = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Laundry machine, dryer,Smart TV or entertainment system",
                            CreatedDate = new DateTime(2025, 9, 13, 16, 30, 38, 584, DateTimeKind.Local).AddTicks(6080),
                            Details = "A luxurious villa with stunning sunset views, private pool, and modern amenities.",
                            ImageUrl = "https://unsplash.com/photos/white-and-brown-concrete-building-near-swimming-pool-during-daytime-GSL3IuuwJv8",
                            Name = "Sunset Shores Villa",
                            Occupancy = 12,
                            Rate = 50000.0,
                            Sqft = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Wi-Fi/internet access,Gym or fitness area",
                            CreatedDate = new DateTime(2025, 9, 13, 16, 30, 38, 584, DateTimeKind.Local).AddTicks(6083),
                            Details = "A luxurious villa with stunning mountain views, private pool, and modern amenities.",
                            ImageUrl = "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = " Mountain Mist Villa",
                            Occupancy = 13,
                            Rate = 67800.0,
                            Sqft = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Comfortable beds and sofas,Home theater room",
                            CreatedDate = new DateTime(2025, 9, 13, 16, 30, 38, 584, DateTimeKind.Local).AddTicks(6086),
                            Details = "A luxurious villa with stunning sunset views, private pool, and modern amenities.",
                            ImageUrl = "https://unsplash.com/photos/a-large-pink-house-with-a-pond-in-front-of-it-S7bDOVuF4R8",
                            Name = " Regal Ridge Villa",
                            Occupancy = 12,
                            Rate = 23400.0,
                            Sqft = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Fully equipped kitchen,Jacuzzi or hot tub",
                            CreatedDate = new DateTime(2025, 9, 13, 16, 30, 38, 584, DateTimeKind.Local).AddTicks(6090),
                            Details = "A luxurious villa with private pool, and modern amenities.",
                            ImageUrl = "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = " Urban Escape Villa",
                            Occupancy = 10,
                            Rate = 12000.0,
                            Sqft = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
